In [4]:
import numpy as np
import pandas as pd
df=pd.read_csv("BHOLE.CSV")
df

A   B    C    D
0  10  20   30   40
1   1   2  NAN  NAN
2   5   6    8  NAN
3   0  11   12  NAN

In [11]:
#jaha p null values hh vha p mean values se replace krdega  if we provide axis as 0 after strategy then row wise mean else if axis=1 or not given then column wise 
from sklearn.preprocessing import Imputer
imr=Imputer(missing_values=np.NAN, strategy='mean')
imr=imr.fit(df)
imputer_data=imr.transform(df.values)
print(imputer_data)

[[10.         20.         30.         40.        ]
 [ 1.          2.         16.66666667 40.        ]
 [ 5.          6.          8.         40.        ]
 [ 0.         11.         12.         40.        ]]


C:\Users\prate\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [12]:
#jaha p null values hh vha p median values se replace krdega  if we provide axis as 0 then row wise mean else if axis=1 or not given then column wise 

from sklearn.preprocessing import Imputer
imr=Imputer(missing_values=np.NAN, strategy='median')
imr=imr.fit(df)
imputer_data=imr.transform(df.values)
print(imputer_data)

[[10. 20. 30. 40.]
 [ 1.  2. 12. 40.]
 [ 5.  6.  8. 40.]
 [ 0. 11. 12. 40.]]


C:\Users\prate\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
